[project]
name = "joblytics"
version = "0.1.0"
description = ""
authors = [
    {name = "Samir Hinojosa", email = "samirhinojosa@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "dbt-postgres (>=1.9.0,<2.0.0)",
    "dbt-core (>=1.10.11,<2.0.0)",
    "beautifulsoup4 (>=4.13.5,<5.0.0)",
    "pydantic (>=2.11.9,<3.0.0)",
    "pydantic-settings (>=2.10.1,<3.0.0)",
    "logging (>=0.4.9.6,<0.5.0.0)",
    "colorlog (>=6.10.1,<7.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-cov = "^7.0.0"
requests-mock = "^1.12.1"
freezegun = "^1.5.5"
faker = "^37.12.0"
ruff = "^0.14.3"
mypy = "^1.18.2"
types-requests = "^2.32.4.20250913"

[tool.poetry.group.notebooks.dependencies]
pandas = "^2.3.3"
tabulate = "^0.9.0"
marimo = "^0.17.7"

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = false
disallow_untyped_defs = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
show_error_codes = true
pretty = true
explicit_package_bases = true

# Relax rules for tests (allow untyped functions)
[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
check_untyped_defs = false

# Ignore missing types for external libs like dbt_*, pandas.*
# [[tool.mypy.overrides]]
# module = ["dbt_*", "pandas.*"]
# ignore_missing_imports = true

[tool.coverage.run]
omit = [
    "*/__init__.py",
    "app/core/logging_config.py",
    "app/domain/exceptions.py",
    "app/infrastructure/http/scraper/scrape_client_error.py",
]
